

#pragma once

typedef enum {
	// INTERNAL USAGE ONLY
	INTERNAL_FTP_RETURN_CODE_MINIMUM = 100,
	INTERNAL_FTP_RETURN_CODE_MAXIMUM = 999,
	//
	FTP_RETURN_CODE_CMD_OK = 200,
    FTP_RETURN_CODE_OPTIONAL_COMMAND_NOT_IMPLEMENTED = 202,
	FTP_RETURN_CODE_SRVC_READY = 220,
	FTP_RETURN_CODE_SYNTAX_ERROR = 500,
	FTP_RETURN_CODE_COMMAND_NOT_IMPLEMENTED = 502,

} FTP_RETURN_CODE;
