

#pragma once

/**
 * @enum value
 */
typedef enum {
	// INTERNAL USAGE ONLY
	INTERNAL_FTP_RETURN_CODE_MINIMUM = 100,
	INTERNAL_FTP_RETURN_CODE_MAXIMUM = 999,
	// 2xx
	FTP_RETURN_CODE_CMD_OK = 200,
	FTP_RETURN_CODE_OPTIONAL_COMMAND_NOT_IMPLEMENTED = 202,
	FTP_RETURN_CODE_SRVC_READY = 220,
	FTP_RETURN_CODE_ENTERING_PASSIVE_MODE = 227,
	FTP_RETURN_CODE_USER_LOGGED_IN = 230,
	FTP_RETURN_CODE_DIR_OP_SUCC = 257,
	// 3xx
	FTP_RETURN_CODE_NEED_PSWD = 331,
	// 4xx
	// 5xx
	FTP_RETURN_CODE_SYNTAX_ERROR = 500,
	FTP_RETURN_CODE_SYNTAX_ERROR_IN_PARAM = 501,
	FTP_RETURN_CODE_COMMAND_NOT_IMPLEMENTED = 502,
	FTP_RETURN_CODE_BAD_SEQUENCE = 503,
	FTP_RETURN_CODE_COMMAND_NOT_IMPLEMENTED_FOR_PARAM = 504,
	FTP_RETURN_CODE_NOT_LOGGED_IN = 530,
} FTP_RETURN_CODE;
