stages:
    - build
    - tests

compile_clang:
    stage: build
    image: ubuntu:24.04
    before_script:
        # install other dependencies
        - apt-get update
        - apt-get install ninja-build wget lsb-release wget software-properties-common gnupg python3-pip --no-install-recommends -y
        # install clang
        - wget https://apt.llvm.org/llvm.sh
        - chmod +x llvm.sh
        - ./llvm.sh 19
        - export CC="clang-19"
        - export CXX="clang++-19"
        # install meson
        - pip install meson --break-system-packages
    script:
        - meson setup build -Dbuildtype=release
        - meson compile -C build
        - meson setup build_debug -Dbuildtype=debug
        - meson compile -C build_debug

compile_gcc:
    stage: build
    image: ubuntu:24.04
    before_script:
        # install gcc + other dependencies
        - apt-get update
        - apt-get install gcc-14 g++-14 python3-pip ninja-build --no-install-recommends -y
        - export CC="gcc-14"
        - export CXX="g++++-19"
        # install meson
        - pip install meson --break-system-packages
    script:
        - meson setup build -Dbuildtype=release
        - meson compile -C build
        - meson setup build_debug -Dbuildtype=debug
        - meson compile -C build_debug
