#include "./debug.h"
#include "utils/string_builder.h"
#include "utils/utils.h"

#include <json/json.h>

// returning a stringbuilder, that makes a string from the http_request, this is useful for
// debugging
StringBuilder* http_request_to_string_builder(const HttpRequest request, bool https) {

	StringBuilder* result = string_builder_init();

	const char* method = get_http_method_string(request.head.request_line.method);
	tstr request_uri = get_request_uri_as_string(request.head.request_line.uri);
	const char* protocol_version =
	    get_http_protocol_version_string(request.head.request_line.protocol_data.version);

	string_builder_append_single(result, "HttpRequest:\n");

	string_builder_append_single(result, "\tMethod:");
	string_builder_append_single(result, method);
	string_builder_append_single(result, "\n");

	STRING_BUILDER_APPENDF(result, return NULL;, "\tRequestURI: %s\n", tstr_cstr(&request_uri));
	tstr_free(&request_uri);

	string_builder_append_single(result, "\tProtocolVersion:");
	string_builder_append_single(result, protocol_version);
	string_builder_append_single(result, "\n");

	STRING_BUILDER_APPENDF(result, return NULL;, "\tSecure : %s\n", https ? "true" : " false");

	for(size_t i = 0; i < TVEC_LENGTH(HttpHeaderField, request.head.header_fields); ++i) {
		HttpHeaderField entry = TVEC_AT(HttpHeaderField, request.head.header_fields, i);

		STRING_BUILDER_APPENDF(result, return NULL;, "\tHeader:\n\t\tKey: %s \n\t\tValue: %s\n",
		                                           tstr_cstr(&entry.key), tstr_cstr(&entry.value));
	}
	STRING_BUILDER_APPENDF(result, return NULL;, "\tBody: " SIZED_BUFFER_FMT " \n",
	                                           SIZED_BUFFER_FMT_ARGS(request.body));
	return result;
}

NODISCARD StringBuilder*
html_from_string(StringBuilder* head_content, // NOLINT(bugprone-easily-swappable-parameters)
                 StringBuilder* script_content, StringBuilder* style_content,
                 StringBuilder* body_content) {

	StringBuilder* result = string_builder_init();

	string_builder_append_single(result, "<!DOCTYPE html><html>");
	string_builder_append_single(result, "<head>");
	string_builder_append_single(result,
	                             "<link rel=\"icon\" href=\"data:image/png;base64,iVBORw0KGgo=\">");
	string_builder_append_single(result, "<meta charset=\"UTF-8\">");
	string_builder_append_single(
	    result, "<meta name=\"description\" content=\"HTML generated by simple C Http Server\">");
	string_builder_append_single(result, "<meta name=\"author\" content=\"Totto16\">");
	string_builder_append_single(result, "<title>Page by Simple C Http Server</title>");
	if(head_content != NULL) {
		string_builder_append_string_builder(result, &head_content);
	}
	if(script_content != NULL) {
		string_builder_append_single(result, "<script type=\"text/javascript\">");

		string_builder_append_string_builder(result, &script_content);
		string_builder_append_single(result, "</script>");
		string_builder_append_single(
		    result,
		    "<noscript> Diese Seite Benötigt Javascript um zu funktionieren :( </noscript>");
	}
	if(style_content != NULL) {
		string_builder_append_single(result, "<style type=\"text/css\">");
		string_builder_append_string_builder(result, &style_content);
		string_builder_append_single(result, "</style>");
	}
	string_builder_append_single(result, "</head>");
	string_builder_append_single(result, "<body>");
	if(body_content != NULL) {
		string_builder_append_string_builder(result, &body_content);
	}
	string_builder_append_single(result, "</body>");
	string_builder_append_single(result, "</html>");

	return result;
}

static JsonValue get_json_auth_repr(const ParsedAuthority authority) {
	JsonObject* const authority_obj = get_empty_json_object();

	{

		JsonObject* const user_obj = get_empty_json_object();

		{
			tstr_static insert_result = json_object_add_entry_cstr(
			    user_obj, "name",
			    new_json_value_string(json_get_string_from_tstr(&authority.user_info.username)));

			assert(tstr_static_is_null(insert_result));

			insert_result = json_object_add_entry_cstr(
			    user_obj, "password",
			    new_json_value_string(json_get_string_from_tstr(&authority.user_info.password)));

			assert(tstr_static_is_null(insert_result));
		}

		tstr_static insert_result =
		    json_object_add_entry_cstr(authority_obj, "user", new_json_value_object(user_obj));

		assert(tstr_static_is_null(insert_result));

		insert_result = json_object_add_entry_cstr(
		    authority_obj, "host",
		    new_json_value_string(json_get_string_from_tstr(&authority.host)));

		assert(tstr_static_is_null(insert_result));

		insert_result = json_object_add_entry_cstr(
		    authority_obj, "port", new_json_value_number((JsonNumber){ .value = authority.port }));

		assert(tstr_static_is_null(insert_result));
	}

	return new_json_value_object(authority_obj);
}

tstr http_request_to_json(const HttpRequest request, bool https, SendSettings send_settings) {

	const char* method = get_http_method_string(request.head.request_line.method);
	const char* protocol_version =
	    get_http_protocol_version_string(request.head.request_line.protocol_data.version);

	JsonObject* const root = get_empty_json_object();

	tstr_static insert_result = json_object_add_entry_cstr(
	    root, "request", new_json_value_string(json_get_string_from_cstr(method)));

	assert(tstr_static_is_null(insert_result));

	JsonObject* const request_uri_obj = get_empty_json_object();

	{

		const ParsedRequestURI request_uri = request.head.request_line.uri;

		// TODO(Totto): factor out some things, like e.g. NULL means not present, port == 0 means
		// default etc
		switch(request_uri.type) {
			case ParsedURITypeAsterisk: {

				insert_result = json_object_add_entry_cstr(
				    request_uri_obj, "type",
				    new_json_value_string(json_get_string_from_cstr("asterisk")));

				assert(tstr_static_is_null(insert_result));

				break;
			}
			case ParsedURITypeAbsoluteURI: {

				insert_result = json_object_add_entry_cstr(
				    request_uri_obj, "type",
				    new_json_value_string(json_get_string_from_cstr("uri")));

				assert(tstr_static_is_null(insert_result));

				JsonObject* const data_obj = get_empty_json_object();

				{

					const ParsedURI uri = request_uri.data.uri;
					const ParsedAuthority authority = uri.authority;

					tstr path_str = get_parsed_url_as_string(uri.path);
					tstr uri_str = get_uri_as_string(uri);

					JsonObject* const path_obj = get_empty_json_object();

					{
						insert_result = json_object_add_entry_cstr(
						    path_obj, "str_form",
						    new_json_value_string(json_get_string_from_tstr(&path_str)));

						assert(tstr_static_is_null(insert_result));
					}

					insert_result = json_object_add_entry_cstr(data_obj, "path",
					                                           new_json_value_object(path_obj));

					assert(tstr_static_is_null(insert_result));

					insert_result = json_object_add_entry_cstr(
					    data_obj, "uri_str",
					    new_json_value_string(json_get_string_from_tstr(&uri_str)));

					assert(tstr_static_is_null(insert_result));

					insert_result = json_object_add_entry_cstr(
					    data_obj, "scheme",
					    new_json_value_string(json_get_string_from_tstr(&uri.scheme)));

					assert(tstr_static_is_null(insert_result));

					JsonValue authority_obj = get_json_auth_repr(authority);

					insert_result =
					    json_object_add_entry_cstr(data_obj, "authority", authority_obj);

					assert(tstr_static_is_null(insert_result));
				}

				insert_result = json_object_add_entry_cstr(request_uri_obj, "data",
				                                           new_json_value_object(data_obj));

				assert(tstr_static_is_null(insert_result));

				break;
			}
			case ParsedURITypeAbsPath: {
				tstr path_str = get_parsed_url_as_string(request_uri.data.path);

				insert_result = json_object_add_entry_cstr(
				    request_uri_obj, "type",
				    new_json_value_string(json_get_string_from_cstr("path")));

				assert(tstr_static_is_null(insert_result));

				JsonObject* const path_obj = get_empty_json_object();

				{
					insert_result = json_object_add_entry_cstr(
					    path_obj, "str_form",
					    new_json_value_string(json_get_string_from_tstr(&path_str)));

					assert(tstr_static_is_null(insert_result));
				}

				insert_result = json_object_add_entry_cstr(request_uri_obj, "data",
				                                           new_json_value_object(path_obj));

				assert(tstr_static_is_null(insert_result));

				break;
			}
			case ParsedURITypeAuthority: {
				const ParsedAuthority authority = request_uri.data.authority;

				insert_result = json_object_add_entry_cstr(
				    request_uri_obj, "type",
				    new_json_value_string(json_get_string_from_cstr("authority")));

				assert(tstr_static_is_null(insert_result));

				JsonValue authority_obj = get_json_auth_repr(authority);

				insert_result = json_object_add_entry_cstr(request_uri_obj, "data", authority_obj);

				assert(tstr_static_is_null(insert_result));

				break;
			}
			default: {
				return tstr_null();
			}
		}
	}

	insert_result =
	    json_object_add_entry_cstr(root, "request_uri", new_json_value_object(request_uri_obj));

	assert(tstr_static_is_null(insert_result));

	insert_result = json_object_add_entry_cstr(
	    root, "protocol_version",
	    new_json_value_string(json_get_string_from_cstr(protocol_version)));

	assert(tstr_static_is_null(insert_result));

	insert_result = json_object_add_entry_cstr(
	    root, "secure", new_json_value_boolean((JsonBoolean){ .value = https }));

	assert(tstr_static_is_null(insert_result));

	JsonArray* const json_headers = get_empty_json_array();

	const size_t header_amount = TVEC_LENGTH(HttpHeaderField, request.head.header_fields);

	for(size_t i = 0; i < header_amount; ++i) {

		HttpHeaderField entry = TVEC_AT(HttpHeaderField, request.head.header_fields, i);

		JsonObject* const json_entry_obj = get_empty_json_object();

		{
			insert_result = json_object_add_entry_cstr(
			    json_entry_obj, "key",
			    new_json_value_string(json_get_string_from_tstr(&entry.key)));

			assert(tstr_static_is_null(insert_result));

			insert_result = json_object_add_entry_cstr(
			    json_entry_obj, "value",
			    new_json_value_string(json_get_string_from_tstr(&entry.value)));

			assert(tstr_static_is_null(insert_result));
		}

		insert_result = json_array_add_entry(json_headers, new_json_value_object(json_entry_obj));

		assert(tstr_static_is_null(insert_result));
	}

	insert_result = json_object_add_entry_cstr(root, "headers", new_json_value_array(json_headers));

	assert(tstr_static_is_null(insert_result));

	insert_result = json_object_add_entry_cstr(
	    root, "body",
	    new_json_value_string(json_get_string_from_tstr_view(tstr_view_from_buffer(request.body))));

	assert(tstr_static_is_null(insert_result));

	JsonObject* const settings_obj = get_empty_json_object();

	{

		JsonObject* const send_settings_obj = get_empty_json_object();

		{

			const tstr compress_format =
			    get_string_for_compress_format(send_settings.compression_to_use);

			insert_result = json_object_add_entry_cstr(
			    send_settings_obj, "compression",
			    new_json_value_string(json_get_string_from_tstr(&compress_format)));

			assert(tstr_static_is_null(insert_result));

			const char* const http_protocol_versio =
			    get_http_protocol_version_string(send_settings.protocol_data.version);

			insert_result = json_object_add_entry_cstr(
			    send_settings_obj, "http_protocol",
			    new_json_value_string(json_get_string_from_cstr(http_protocol_versio)));

			assert(tstr_static_is_null(insert_result));
		}

		insert_result = json_object_add_entry_cstr(settings_obj, "send_settings",
		                                           new_json_value_object(send_settings_obj));

		assert(tstr_static_is_null(insert_result));
	}

	insert_result =
	    json_object_add_entry_cstr(root, "settings", new_json_value_object(settings_obj));

	assert(tstr_static_is_null(insert_result));

	JsonValue val = new_json_value_object(root);

	const tstr str = json_value_to_string(&val);

	free_json_value(&val);

	return str;
}

StringBuilder* http_request_to_html(const HttpRequest request, bool https,
                                    SendSettings send_settings) {

	StringBuilder* body = string_builder_init();

	const char* method = get_http_method_string(request.head.request_line.method);
	tstr request_uri = get_request_uri_as_string(request.head.request_line.uri);
	const char* protocol_version =
	    get_http_protocol_version_string(request.head.request_line.protocol_data.version);

	string_builder_append_single(body, "<h1 id=\"title\">HttpRequest:</h1><br>");

	string_builder_append_single(body, "<div id=\"request\"><div>Method:");
	string_builder_append_single(body, method);
	string_builder_append_single(body, "</div>");

	STRING_BUILDER_APPENDF(body, return NULL;
	                       , "<div>RequestURI: %s</div>", tstr_cstr(&request_uri));
	tstr_free(&request_uri);

	string_builder_append_single(body, "<div>ProtocolVersion:");
	string_builder_append_single(body, protocol_version);
	string_builder_append_single(body, "</div>");
	STRING_BUILDER_APPENDF(
	    body, return NULL;,
	                      "<div>Secure : %s</div><button id=\"shutdown\"> Shutdown </button></div>",
	                      https ? "true" : "false");
	string_builder_append_single(body, "<div id=\"header\">");
	for(size_t i = 0; i < TVEC_LENGTH(HttpHeaderField, request.head.header_fields); ++i) {

		HttpHeaderField entry = TVEC_AT(HttpHeaderField, request.head.header_fields, i);

		STRING_BUILDER_APPENDF(
		    body, return NULL;
		    , "<div><h2>Header:</h2><br><h3>Key:</h3> %s<br><h3>Value:</h3> %s</div>",
		    tstr_cstr(&entry.key), tstr_cstr(&entry.value));
	}

	string_builder_append_single(body, "</div> <div id=\"settings\">");
	string_builder_append_single(body, "<h1>Settings:</h1> <br>");
	{
		string_builder_append_single(body, "</div> <div id=\"send_settings\">");
		string_builder_append_single(body, "<h2>Send Settings:</h2> <br>");

		const tstr comp_format = get_string_for_compress_format(send_settings.compression_to_use);

		STRING_BUILDER_APPENDF(body, return NULL;
		                       , "<h3>Compression:</h3> " TSTR_FMT, TSTR_FMT_ARGS(comp_format));
		STRING_BUILDER_APPENDF(body, return NULL;, "<h3>HTTP Protocol:</h3> %s",
		                                         get_http_protocol_version_string(
		                                             send_settings.protocol_data.version));
		string_builder_append_single(body, "</div>");
	}
	string_builder_append_single(body, "</div>");

	string_builder_append_single(body, "</div> <div id=\"body\">");
	STRING_BUILDER_APPENDF(body, return NULL;, "<h1>Body:</h1> <br>" SIZED_BUFFER_FMT "",
	                                         SIZED_BUFFER_FMT_ARGS(request.body));
	string_builder_append_single(body, "</div>");

	// style

	StringBuilder* style = string_builder_init();
	string_builder_append_single(
	    style, "body{background: linear-gradient( 90deg, rgb(255, 0, 0) 0%, rgb(255, 154, 0) 10%, "
	           "rgb(208, 222, 33) 20%, rgb(79, 220, 74) 30%, rgb(63, 218, 216) 40%, rgb(47, 201, "
	           "226) 50%, rgb(28, 127, 238) 60%, rgb(95, 21, 242) 70%, rgb(186, 12, 248) 80%, "
	           "rgb(251, 7, 217) 90%, rgb(255, 0, 0) 100% );}"
	           "#request {display: flex;justify-content: center;gap: 5%;color: #1400ff;text-align: "
	           "center;align-items: center;}"
	           "#header {display:flex; flex-direction: column;align-items: center;overflow-wrap: "
	           "anywhere;text-align: center;word-wrap: anywhere;}"
	           "#body {padding: 1%;text-align: center;border: solid 4px black;margin: 1%;}"
	           "#shutdown {border: none;cursor: crosshair;opacity: .9;padding: 16px "
	           "20px;background-color: #c7ff00;font-weight: 900;color: #000;}"
	           "#title{text-align: center;}"
	           "#settings {display:flex; flex-direction: column;align-items: center;overflow-wrap: "
	           "anywhere;text-align: center;word-wrap: anywhere;}"
	           "#send_settings {display:flex; flex-direction: column;align-items: "
	           "center;overflow-wrap: "
	           "anywhere;text-align: center;word-wrap: anywhere;}"

	);

	// script
	StringBuilder* script = string_builder_init();
	string_builder_append_single(
	    script, "function requestShutdown(){"
	            "	document.querySelector('button').onclick = ()=>{"
	            "		let shutdownUrl = `${location.protocol}//${location.host}/shutdown`;"
	            "		const xhr = new XMLHttpRequest();"
	            "		xhr.onload = (response)=>{"
	            "			if(xhr.status == 200){"
	            "				alert(\"Successfully Shut Down the server!\");"
	            "			}else{"
	            "				console.error(xhr);"
	            "				alert(\"Couldn't Shut Down the Server!\");"
	            "			}"
	            "		};"
	            "		xhr.onerror = (err)=>{"
	            "			console.error(err);"
	            "			alert(\"Couldn't Shut Down the Server!\");"
	            "		};"
	            "		xhr.open(\"GET\", shutdownUrl);"
	            "		xhr.send();"
	            "	}"
	            "}"
	            "window.addEventListener('DOMContentLoaded',requestShutdown);");

	StringBuilder* html_result = html_from_string(NULL, script, style, body);
	return html_result;
}
