name: Musl CI

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-24.04
    container: alpine:3.22

    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Linux GCC (musl)
            use-clang: false

          - name: Linux Clang (musl)
            use-clang: true


    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add wget meson ca-certificates samurai git openssl-dev openssl pkgconf zstd-dev zlib-dev brotli-dev gmp-dev linux-pam-dev ${{ ( matrix.config.use-clang == true ) && 'clang20' || 'gcc musl-dev g++' }}
          echo "CC=${{ matrix.config.use-clang == true && 'clang-20' || 'gcc' }}" >> "$GITHUB_ENV"
          echo "CXX=${{ matrix.config.use-clang == true && 'clang++-20' || 'g++' }}" >> "$GITHUB_ENV"

      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
  
      - name: Configure
        run: meson setup build -Dbuildtype=release -Dsecure=enabled -Dcompression_features=zstd,br,deflate,gzip,compress -Dother_features=bcrypt,pam

      - name: Build
        run: meson compile -C build
